:REVEAL_PROPERTIES:
#+OPTIONS: reveal_embed_local_resources:t
#+OPTIONS: reveal_width:1600 reveal_height:1000
#+OPTIONS: num:nil toc:nil author:nil email:t timestamp:t title:t
#+REVEAL_TITLE_SLIDE: %t <br> %e <br> Compiled %T <br> <br> <a href="https://tinyurl.com/23sj4ssa"> The Link to the PDF version </a> <br> <a href="https://mj-ramirez.github.io/Cerebral_Angiopathy_talk/"> The Link to the HTML5 version </a>
#+REVEAL_INIT_OPTIONS: margin: 0.001, minScale:0.2, maxScale:2.5, transition:'convex'
#+REVEAL_THEME: solarized
#+REVEAL_SLIDE_FOOTER: Cerebral Amyloid Angiopathy
#+REVEAL_EXTRA_CSS: ./local.css
#+REVEAL_INIT_OPTIONS: slideNumber:true
#+REVEAL_DEFAULT_SLIDE_BACKGROUND: https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/ARU%20Presentation%20Feb%202025/Images_ARU_vascular1/Hoppman.jpeg
#+REVEAL_DEFAULT_SLIDE_BACKGROUND_OPACITY:0.2
#+REVEAL_SPEED:
:END:
#+attr_html: :width 12% :align right
https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/ARU%20Presentation%20Feb%202025/Images_ARU_vascular1/NHS.png

#+Author: Kirthivasan Ramanatham
#+Email: r.kirthivasan@nhs.net
#+Title: Cerebral Amyloid Angiopathy

* Cerebral Amyloid Angiopathy
@@html:<center>@@
Kirthivasan Ramanatham\\
Consultant Stroke Physician\\
Stroke Unit Broomfield Hospital\\
Mid & South Essex Hospital Trust\\
February 2025
** Table of Contents
   :PROPERTIES:
   :UNNUMBERED: notoc
   :END:
#+REVEAL_TOC: headlines 1
* Introduction
Cerebral amyloid angiopathy (CAA) is a chronic, degenerative cerebrovascular
disease caused by deposition of amyloid protein in cerebral vessel walls.

* Case Presentations
- 3 tales – one unifying diagnosis Thrombosis, haemorrhage and inflammation– all
  in one.
  - Quiz
  - Diagnosis/phenotypes
  - Conundrums
** Case Number 1: A 65 years old female
*** Presentation
#+ATTR_REVEAL: :frag (appear)
- Sept 2015
  - Presented to stroke with intermittent confusion, subtle left facial weakness
  - CT reveals extensive hypodensity right temporoparietal lobe
  - MRI revealed DWI hyperintensity/T2 and FLAIR hyperintensities right temporal lobe – no enhancement
  - Surveillance MRI revealed complete resolution of abnormality
- April 2020
  - Right arm numbness and aphasia for an hour followed by confusion
  - CT head showed oedema in left temporoparietal area
  - MRI head with contrast T2 hyperintensity left temporoparietal region with no enhancement
  - MRI repeated 2 months later - resolution

*** Imaging: CT Head September 2015
@@html:<center><video controls width="1600" height=autosrc="https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/Cerebral%20Angiopathy%20Talk/Images/Case%20One.mp4"></video>@@
** Case Number 2: A 67 years old male
- PMH: on anticoagulant for Anti Phospholipid Antibody syndrome
*** Presentation
#+ATTR_REVEAL: :frag (appear)
- Jan 2019
  - Presented with sudden onset pins and needles right hand
  - CT Head and MRI revealed a focal SAH
- July 2024
  - 2 x episodes of stereotyped events at 6 and 7 am – right hand tingling and
    slurred speech
  - Whilst an inpatient had recurrent episode of right facial numbness, tingling of right hand and slurred speech
  - MRI
  - Resolved and home on continued treatment
- Jan 2025
  - Several episodes of recurrent stereotyped episodes of right facial numbness, tingling in the right hand and slurred speech
*** Imaging: MRI Brain July 2024

#+ATTR_HTML: :width 50%:
@@html:<center>@@
https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/Cerebral%20Angiopathy%20Talk/Images/MRI%20Imaging%20Case2%20copy.jpg
** Case Number 3: A 65 years old female
*** Presentation
#+ATTR_REVEAL: :frag (appear)
- July 2022: Two episodes of Left facial droop, left sided paresthesia and dysarthria
- May 2023: Transient right hemifield visual loss
- September 2023: Left lower quadrantanopia, left arm drift
- January 2025:
  - Tingling of the left hand
  - MRI revealed moderate white matter hyperintensities, few cortical microbleeds L>R
*** Imaging: MRI Brain January 2025
#+ATTR_HTML: :width 100%:
@@html:<center>@@https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/Cerebral%20Angiopathy%20Talk/Images/MRI%20Case%20Number3%20copy.jpg
* Criteria for Diagnosis
Charidimou, Boulouis & Frosch et al. (2022) The Boston Criteria Version 2.0 for
Cerebral Amyloid Angiopathy: A Multicentre, Retrospective, MRI-neuropathology
Diagnostic Accuracy Study, The Lancet. Neurology. [[https://pubmed.ncbi.nlm.nih.gov/35841910/][PubMed]]
** Definite CAA
- Requires postmortem confirmation
- Pathological evidence of amyloid-β deposition in cortical/leptomeningeal vessels
- Documentation of lobar hemorrhage (macro/microbleed, cortical superficial siderosis [cSS], or intracerebral hemorrhage [ICH])
** Probable CAA
- Clinical-imaging criteria (without pathology)
- Age ≥50 years
- MRI evidence of ≥1 of the following
- ≥2 strictly lobar hemorrhages (spontaneous ICH, cerebral microbleeds [CMBs], or cSS)
- One lobar hemorrhage + focal/disseminated cSS (≥3 sulci)
- Exclusion of other causes (e.g., hypertension, anticoagulation, trauma, hemorrhagic tumor)
** Possible CAA
- Clinical-imaging criteria
- Age ≥50 years
- MRI evidence of one strictly lobar hemorrhage (ICH, CMB, or cSS)
- No alternative cause identified
** Supporting Features (Not required but suggestive)
- Neuroimaging:
  - Acute convexity subarachnoid hemorrhage (non-traumatic)
  - Severe white matter hyperintensities (posterior-predominant)
  - Enlarged perivascular spaces (centrum semiovale >20 count)
- Genetic:
  - APOE ε4 allele (risk factor)
  - Family history of CAA or hereditary forms (e.g., APP mutations)
** Unifying diagnosis ? discussion
- Single pathophysiological condition causing this
- There is no specific treatment
- Progressive inexorable course with mortality due to
  neurodegenerative/cognitive or strokes (ischemic or hemorrhagic)

** Typical radiological findings TFNE
Transient focal neurological episodes
#+ATTR_HTML: :width 40% :align left
https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/Cerebral%20Angiopathy%20Talk/Images/Illutstration%20of%20ICH.jpg

- Convexity subarachnoid hemorrhage (cSAH)
- Lobar Intracranial Haemorrhage (ICH)
- Cerebral micro bleeds (CMB)
- Enlarged Perivascular Spaces (EPVS)
- Ischemic stroke
- Subdural haemorrhage
- Cortical superficial siderosis (cSS)
- White matter hyperintensities (WMH)
- Intraventricular bleeding

** Possible/probable phenotypes associated with higher risk of ICH
- Transient focal neurological event
- White matter hyper intensities
- Disseminated cortical superficial siderosis
- Lobar ICH with micro bleeds
- Cortical atrophy
** Typical imaging features of CAA
- Cortico-subcortical microhemorrhages or petecchial hemorrhages
- Large and confluent areas of white matter hyperintensities in T2/FLAIR-weighted images and scattered microbleeds on gradient-echo sequences
- (Recurrent) lobar ICH - with finger like projections
- Focal cortical SAH
- Subdural haemorrhages
- Basal ganglia haemorrhages
** Transient focal neurological episodes (TFNEs)
- Brief disturbances of motor, somatosensory, visual or language functions
- Frequently recurrent stereotyped episodes of focal disturbances
- Often presenting of transient parenthesis of the mouth or hand
- Very close resemblance to TIAs
- As these are typically thrombotic, they do not pose a ICH risk
** Markers for Amyloid angiopathy
- Clinical
- Imaging
- Pathological
- CSF
- Genetic
- Emerging
** Superficial Siderosis
#+ATTR_HTML: :width 90%
@@html:<center>@@
https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/Cerebral%20Angiopathy%20Talk/Images/Siderosis.jpg

* Management and Treatment Options
** Managing thrombotic conditions in CAA
- Balancing Ischemic vs. Hemorrhagic Stroke Risks
- Anticoagulation Dilemmas in Atrial Fibrillation
- Antiplatelet Therapy After Intracerebral Hemorrhage
- Using imaging biomarkers for risk stratifcation
- Emerging Approaches and Research Gaps
- LAAO
- DOAC Novel biomarker
- Immunosuppression
- Biological treatments
** Risk of Intracranial Bleeding
#+ATTR_HTML: :width 55% :align left
https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/Cerebral%20Angiopathy%20Talk/Images/MICON%20Illustration.jpg

- Prior ICH 2 = points
- cSS = 1 point
- APOE e4/e2 = 1 point
- O points 3.7 risk of bleed
- 3 points – 25% risk
** CAA, Atrial Fibrillation and Anticoagulation
#+ATTR_HTML: :width 70%
@@html:<center>@@
https://filedn.eu/lb297pjeroJ5OLJWy2IKwmV/Cerebral%20Angiopathy%20Talk/Images/Illustration%20AF%20and%20CAA%20copy.jpg

** Antithrombotic Therapy After Intracerebral Haemorrhage
- RESTART trial: Anticoagulation
  - The notion that anticoagulation should be permanently avoided following ICH has been challenged and a more nuanced approach is suggested
  - One such nuance however is that certain phenotypes of CAA confer the highest rebleed risk
- Antiplatelets (More controversial)
  - RESTART AP/SoSTART – small and underpowered but initial results are appearing no increase in risk. ASPIRING is recruiting and we are participating
  - Metaanalysis suggests modest increase in ICH with antiplatelets with an RR 1.3-1.5 but is it outweighed by prevention of thrombotic events? JURY IS OUT

** Novel treatment modalities
- Monoclonal Antibodies Targeting Amyloid-β
- β-Secretase (BACE) Inhibitors
- γ-Secretase Modulator
- Amyloid Aggregation Inhibitors
- Active Immunotherapy

* Prognosis and Outcomes
Best, Ambler & Wilson et al. (2021) Development of Imaging-Based Risk Scores for Prediction of Intracranial Haemorrhage and Ischaemic Stroke in Patients Taking Antithrombotic Therapy after Ischaemic Stroke or Transient Ischaemic Attack: A Pooled Analysis of Individual Patient Data from Cohort Studies, The Lancet. Neurology.
* References
@@html:<br>@@
Lou, Safdar & Mehdiratta et al. (2008) The HAT Score: A Simple Grading Scale for
Predicting Hemorrhage after Thrombolysis, Neurology. [[https://pubmed.ncbi.nlm.nih.gov/18955684][PubMed]]

@@html:<br>@@
Best, Ambler & Wilson et al. (2021) Development of Imaging-Based Risk Scores for
Prediction of Intracranial Haemorrhage and Ischaemic Stroke in Patients Taking
Antithrombotic Therapy after Ischaemic Stroke or Transient Ischaemic Attacks, The Lancet.
Neurology. [[https://pubmed.ncbi.nlm.nih.gov/31130428/][PubMed]]

@@html:<br>@@
Charidimou, Shoamanesh & Salman et al. (2017) Cerebral Amyloid Angiopathy,
Cerebral Microbleeds and Implications for Anticoagulation Decisions: The Need
for a Balanced Approach, International Journal of Stroke. [[https://pubmed.ncbi.nlm.nih.gov/29125055/][PubMed]]

@@html:<br>@@
DeSimone, Graff & El et al. (2017) Cerebral Amyloid Angiopathy, Journal of the
American College of Cardiology. [[https://pubmed.ncbi.nlm.nih.gov/28838368/][PubMed]]
